baseURL = "https://c0ravx.github.io/"
languageCode = "en-us"
title = "c0ravx"
theme = "ezhil"
paginate = 5

publishDir = "docs"

copyright = "c0ravx - 2022"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "ezhil-demo"

summaryLength = 20

[params]
	subtitle = "net is vast and infinite"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "dark" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/c0ravx"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/c0ravx"

# [taxonomies]
#   tag = "tags"
